package com.example.user.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import com.example.user.bean.AppInfo;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "APP_INFO".
*/
public class AppInfoDao extends AbstractDao<AppInfo, String> {

    public static final String TABLENAME = "APP_INFO";

    /**
     * Properties of entity AppInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property PackageName = new Property(0, String.class, "packageName", true, "PACKAGE_NAME");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Memory = new Property(2, String.class, "memory", false, "MEMORY");
        public final static Property Lock = new Property(3, boolean.class, "lock", false, "LOCK");
        public final static Property System = new Property(4, boolean.class, "system", false, "SYSTEM");
    };


    public AppInfoDao(DaoConfig config) {
        super(config);
    }
    
    public AppInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"APP_INFO\" (" + //
                "\"PACKAGE_NAME\" TEXT PRIMARY KEY NOT NULL ," + // 0: packageName
                "\"NAME\" TEXT," + // 1: name
                "\"MEMORY\" TEXT," + // 2: memory
                "\"LOCK\" INTEGER NOT NULL ," + // 3: lock
                "\"SYSTEM\" INTEGER NOT NULL );"); // 4: system
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"APP_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AppInfo entity) {
        stmt.clearBindings();
 
        String packageName = entity.getPackageName();
        if (packageName != null) {
            stmt.bindString(1, packageName);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String memory = entity.getMemory();
        if (memory != null) {
            stmt.bindString(3, memory);
        }
        stmt.bindLong(4, entity.getLock() ? 1L: 0L);
        stmt.bindLong(5, entity.getSystem() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AppInfo entity) {
        stmt.clearBindings();
 
        String packageName = entity.getPackageName();
        if (packageName != null) {
            stmt.bindString(1, packageName);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String memory = entity.getMemory();
        if (memory != null) {
            stmt.bindString(3, memory);
        }
        stmt.bindLong(4, entity.getLock() ? 1L: 0L);
        stmt.bindLong(5, entity.getSystem() ? 1L: 0L);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public AppInfo readEntity(Cursor cursor, int offset) {
        AppInfo entity = new AppInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // packageName
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // memory
            cursor.getShort(offset + 3) != 0, // lock
            cursor.getShort(offset + 4) != 0 // system
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AppInfo entity, int offset) {
        entity.setPackageName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMemory(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLock(cursor.getShort(offset + 3) != 0);
        entity.setSystem(cursor.getShort(offset + 4) != 0);
     }
    
    @Override
    protected final String updateKeyAfterInsert(AppInfo entity, long rowId) {
        return entity.getPackageName();
    }
    
    @Override
    public String getKey(AppInfo entity) {
        if(entity != null) {
            return entity.getPackageName();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
